Edit an entry
Han-Zhang-fuze/code-journal pull request #8
Opened 2022-06-02 20:25 UTC by Han-Zhang-fuze

![Jun-02-2022 13-24-00](https://user-images.githubusercontent.com/103379415/171731841-583054e6-96b7-4f15-bef3-b8fbc18205f1.gif)

2022-06-03 21:41 UTC, Han-Zhang-fuze commented
![Jun-03-2022 14-39-25](https://user-images.githubusercontent.com/103379415/171957623-3f452599-5f4b-4065-ad8f-201e69e69636.gif)

2022-06-04 17:38 UTC, Han-Zhang-fuze commented
![Jun-04-2022 10-19-41](https://user-images.githubusercontent.com/103379415/172019140-6b92ca74-2f14-4f9a-86ec-81f5c85e6d03.gif)

2022-06-04 17:49 UTC, codingcodymiller requested changes

2022-06-04 17:49 UTC, codingcodymiller commented on js/main.js
> +            $currentListItem.replaceWith($createRow);
Don't you already have a function that generates a single DOM tree for a single Entry?

2022-06-04 18:42 UTC, codingcodymiller approved these changes

2022-06-04 18:43 UTC, merged